#!/bin/sh
#
# Wrapper script for winetricks compatability
#
# Copyright (C) 2021 Dean M Greer
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
#


export CX_INSTALL="@@APPLICATIONS@@/CrossOver.app"
export CX_PATH="${CX_INSTALL}/Contents/SharedSupport/CrossOver"
export CX_BOTTLE="${CX_BOTTLE:-default}"
export CX_BOTTLE_PATH="${CX_BOTTLE_PATH:-$HOME/Library/Application Support/CrossOver/Bottles}"

if [ ! -d "${CX_BOTTLE_PATH}/${CX_BOTTLE}" ]; then
    echo ""
    echo "Please set \$CX_BOTTLE env to your CrossOver Bottle"
    echo "Or set your desired bottle to default from the CrossOver UI"
    exit
fi

export WINE="${CX_PATH}/bin/wine"
export WINE64="${WINE}"
export WINESERVER="${WINE}server"
export WINEPREFIX="${CX_BOTTLE_PATH}/${CX_BOTTLE}"
export WINETRICKS_WINE_VERSION=$(sed -n '2p' "${CX_PATH}/share/wine/wine.inf" | tr ' ' '\a' | awk -F'\a' '{print $4}')
export WINEDEBUG=-all

exec winetricks "${@}"
